// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PathologyFormApp.Models;

#nullable disable

namespace PathologyFormApp.Migrations
{
    [DbContext(typeof(PathologyContext))]
    [Migration("20250501044200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PathologyFormApp.Models.PathologyRequisitionForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CRNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Character")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicalDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consultant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeOfCollection")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeOfReceivingSpecimen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gravida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrossDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HormoneTherapy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPDNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Impression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LMP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabRefNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabRefNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LaboratoryFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LastingDays")
                        .HasColumnType("int");

                    b.Property<string>("Menopause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenopauseAge")
                        .HasColumnType("int");

                    b.Property<int?>("MensesOnset")
                        .HasColumnType("int");

                    b.Property<string>("MicroSectionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MicroscopicExamination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfSpecimens")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoOfSpecimenReceived")
                        .HasColumnType("int");

                    b.Property<string>("OPD_IPD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperativeFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Para")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pathologist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PathologistDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostOperativeDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousHPCytReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialStains")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecimenNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadedFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRayUSGCTMRIFindings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PathologyRequisitionForms");
                });
#pragma warning restore 612, 618
        }
    }
}
